name: GCP-Cleaner

on:
  schedule:
    - cron: '30 1 15 * *'
  workflow_dispatch:

env:
  GCP_KEY : ${{ secrets.GCP_PASSWORD }}

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
      credentials_json: '${{ GCP_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud container images list'

      # configure based on your registry
    - uses: 'docker/login-action@v2'
      with:
        registry: gcr.io
        username: ${{ secrets.GCP_USERNAME }}
        password: ${{ GCP_KEY }}

      # customize based on the gcr-cleaner flags
    - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
      with:
        args: >-
          -repo=gcr.io/alconost-sandbox/testimage
          -grace=10s
